[package]
name = "codegen_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui-modal = "0.4.0"
egui_extras = "0.28.1"
hmac = "0.12.1"
image = "0.24.3"
regex = "1.10.6"
sha1 = "0.10.6"
